### ISSUE TITLE
Była jakaś zmiana w kodowaniu?

### ISSUE THREAD

**Issue by marekmarcos** [cichy1173/decovid-vaccine-passport#2]
mój kod nie zaczyna się od HC1 i Twój program go nie rozkodowuje
ValueError("Invalid base45 string")

**Comment by cichy1173** [comment]
Czy Twój kod to paszport covidowy? Przed jego wypuszczeniem osoby zaszczepione dostawały inny rodzaj kodów QR, które nie były zgodne z paszportem covidowym.

**Comment by marekmarcos** [comment]
tak, paszport. To coś innego? Jak to rozkodować?

**Comment by marekmarcos** [comment]
Jak chcesz się pobawić to tu masz cały tekst z qr&#39;a :  1;0j1j3lUlZ77XxGINnxJINjmaUi5SAXzPcrViR9dRvbQwum9O+8N9ttYbJZ6jY8LF4AWQvUnqDmib/cHMQmirqSJOiJeUDwcqgIN7BY+HQtAFyKuvYzhHeXu7elFbPmKK20ijSBIW2Uskdpce4NADTcHfOQ6jmDh56iy7Y+I/WpUipWzOxD  Dnia 7 listopada 2021 21:04 cichy1173 ***@***.***&gt; napisał(a):   Czy Twój kod to paszport covidowy? Przed jego wypuszczeniem osoby zaszczepione dostawały inny rodzaj kodów QR, które nie były zgodne z paszportem covidowym.  —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com unsubscribe .  Triage notifications on the go with GitHub Mobile for  apps.apple.com iOS  or  play.google.com Android .

**Comment by cichy1173** [comment]
Cześć. 
Sprawdziłem repozytorium kodów testowych dla deweloperów i nie widzę tam żadnej zmiany od czasów stworzenia tej aplikacji. Przyznam szczerze, że nie wiem kto wystawił Ci taki certyfikat. Paszport covidowy europejski zaczyna się od znaków `HC1.`
Certyfikat covidowy jest kodowany zgodnie z poniższym schematem: 
![obraz](https://user-images.githubusercontent.com/32648503/140723019-7f7f9ca8-ded5-48ba-b636-ea82fb1147dd.png)
W repozytorium znajdziesz skrócone sprawozdanie opisujące działanie aplikacji.

**Comment by cichy1173** [comment]
Ze względu na brak odpowiedzi oraz wyjaśnienie sytuacji, zamykam wątek.
